### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by lowks** [iroddis/asdf-R#1]
Hi,
I am running on High Sierra
and version of `asdf` = `v0.4.1`
when I try to do `asdf install R 3.4.3`

I get and error like this:

```
checking for Fortran 77 name-mangling scheme... configure: error: in `/var/folders/74/87lvr3dn181bqfph2vtkc2n40000gn/T/R-3.4.3':
configure: error: cannot compile a simple Fortran program
See `config.log' for more details```

**Comment by smackesey** [comment]
I also had this problem. I fixed it by installing gcc, as the README says (`brew install gcc` on MacOS).

**Comment by lowks** [comment]
I installed `gcc` on mac and got this: 
```
configure: error: --with-x=yes (default) and X11 headers/libs are not available
```

**Comment by neil-joule** [comment]
`R_CONFIGURE_OPTIONS=--with-x=no asdf install R 3.5.1` worked for me.

**Comment by nderraugh** [comment]
`R_CONFIGURE_OPTIONS=--with-x=no asdf install R 3.5.1` worked for me.
