### ISSUE TITLE
[ubuntu 18] missing dependencies in readme

### ISSUE THREAD

**Issue by WannesFransen1994** [iroddis/asdf-R#11]
Hello, just a small issue to mention some missing dependencies in the readme in order to install version 3.6.3:

```bash
sudo apt install libbz2-dev liblzma-dev libpcre3 libpcre3-dev
```

operating system:
```
> $ cat /etc/os-release                                                                                                                 
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
```

Not an expert in this field, but thought mentioning would be worth it. Feel free to close this issue if you find this irrelevant (I've already fixed it on my local setup).

**Comment by iroddis** [comment]
Thanks for the feedback, I'm updating the documentation now.
