### ISSUE TITLE
Failed to install in macOS

### ISSUE THREAD

**Issue by SuperBo** [iroddis/asdf-R#7]
I met this error when install R in macOS 10.15.5

```sh
$ asdf install R 3.6.3
configure: error: --with-x=yes (default) and X11 headers/libs are not available
```

**Comment by swt30** [comment]
I got this to work by first installing xquartz through Homebrew  (`brew cask install xquartz`)

**Comment by BennyHoward** [comment]
> I got this to work by first installing xquartz through Homebrew (`brew cask install xquartz`)

I had the same issue today.  Installing `xquartz` fixed it.
I think we should add this to the **README.md** file as a step **iii** under **Dependencies** -> **Mac**.

**Comment by BennyHoward** [comment]
This is in the README.md file now.  So I think we can close this.
